### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by claudiodonati** [Finn-Lab/EukCC#1]
I am trying to install EukCC, and I am running in the following issue:

(eukcc) root@cebe688dfe44:/Junk/EukCC# pip3 install .
Processing /Junk/EukCC
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: ete3 in /usr/local/lib/python3.7/dist-packages (from eukcc==0.1) (3.1.1)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.7/dist-packages (from eukcc==0.1) (5.3)
ERROR: Could not find a version that satisfies the requirement gzip (from eukcc==0.1) (from versions: none)
ERROR: No matching distribution found for gzip (from eukcc==0.1)

However, gzip is installed. 

(eukcc) root@cebe688dfe44:/Junk/EukCC# gzip --version
gzip 1.9
Copyright (C) 2017 Free Software Foundation, Inc.
Copyright (C) 1993 Jean-loup Gailly.
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <https://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

Written by Jean-loup Gailly.

Any hint?

**Comment by openpaul** [comment]
Thank you for testing EukCC. This was fixed now in 7151b59, I hope the install works now for you with the newest version.
