### ISSUE TITLE
Failure placementReduced.jplace has no placements

### ISSUE THREAD

**Issue by sarah872** [Finn-Lab/EukCC#10]
Hi,
I was running `eukcc` on an illumina assembly of a big eukaryotic genome and got the following error:
```
0/05/2020 15:25:11:  Starting EukCC
10/05/2020 15:34:36:  Running GeneMark-ES
10/05/2020 21:04:04:  Extracting protein locations
10/05/2020 21:04:05:  Searching for proteins to place in the tree
10/05/2020 21:04:09:  Processing Hmmer results
10/05/2020 21:04:16:  Placing proteins in tree
Uncaught exception: Failure("eukcc_wgs-holobiont/workfiles/pplacer/placementReduced.jplace has no placements!")
Fatal error: exception Failure("eukcc_wgs-holobiont/workfiles/pplacer/placementReduced.jplace has no placements!")
10/05/2020 21:06:49:  an error occured while executing guppy
10/05/2020 21:06:49:  No estimates were written
```
The `eukcc_wgs-holobiont/workfiles/pplacer/placementReduced.jplace` exists and is not empty. I tried re-running but got the same error.

**Comment by openpaul** [comment]
Hello, could you provide me with the `eukcc_wgs-holobiont/workfiles/pplacer/placementReduced.jplace` file (If possible all files in the pplacer folder would be perfect) ? It might be that no placement has enough support and is thus discarded. I might need to adjust the parameters and/or make the error message more meaningful.

**Comment by sarah872** [comment]
[pplacer.zip](https://github.com/Finn-Lab/EukCC/files/5339659/pplacer.zip)

**Comment by openpaul** [comment]
So your placements had a posterior probability less than 0.4 (default), thus EukCC assumed they are not good enough to consider this placement valid.
You can however change this threshold using the `--minPlacementLikelyhood` parameter. You could set it to 0 to deactivate this filtering. I would think thats also a valid parameter setting, although less conservative.

**Comment by openpaul** [comment]
Let me know if adjusting the parameter works for you. Might be worth writing about it in the documentation then.

**Comment by sarah872** [comment]
Yes, thank you, setting it to 0 worked!
