### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by gchevignon** [Finn-Lab/EukCC#13]
Hello,

I have tried to run eukcc on a protein dataset but I got this error:

eukcc --db /home1/datawork/gchevign/Data.dir/eukcc_db.dir/eukccdb/ --outdir /home1/datawork/gchevign/Bonamia_RNAseq.dir --ncores 2 --proteins /home1/datawork/gchevign/Bonamia_RNAseq.dir/7-annotation.dir/1-transdecoder.dir/Trinity_2.fasta.transdecoder_clean.pep

11/27/2020 13:27:58:  Starting EukCC
11/27/2020 13:28:02:  MAG succesfully placed in tree
11/27/2020 13:28:02:  Using pressed hmms from last run
11/27/2020 13:28:02:  294381 taxid not found
Traceback (most recent call last):
  File "/home1/datawork/gchevign/Soft.dir/eukcc/bin/eukcc", line 10, in <module>
    sys.exit(main())
  File "/home1/datawork/gchevign/Soft.dir/eukcc/lib/python3.6/site-packages/eukcc/__main__.py", line 222, in main
    _ = m.inferLineage(m.placements[m.cfg["placementMethod"]])
  File "/home1/datawork/gchevign/Soft.dir/eukcc/lib/python3.6/site-packages/eukcc/workflow.py", line 306, in inferLineage
    common = set(lngs[0])
IndexError: list index out of range

**Comment by openpaul** [comment]
I could not reproduce this bug, could you supply me with your dataset? Maybe the bug was already solved in the newest version (0.3)?

**Comment by diedie9** [comment]
Hello,
I also have this error when run eukcc.
Do you debug it ? My eukcc version is 3.2

04/02/2022 14:03:28:  Starting EukCC - yes
04/02/2022 14:03:28:  Running GeneMark-ES
04/02/2022 15:08:29:  Extracting protein locations
04/02/2022 15:08:29:  Searching for proteins to place in the tree
04/02/2022 15:08:41:  Processing Hmmer results
04/02/2022 15:08:48:  Placing proteins in tree
04/02/2022 15:13:40:  MAG succesfully placed in tree
04/02/2022 15:13:40:  378 hmm profiles need to be used for estimations
04/02/2022 15:13:40:  Concatenating hmms, this might take a while (IO limited)
04/02/2022 15:13:48:  Pressing hmms
04/02/2022 15:13:50:  Running hmmer for chosen locations
04/02/2022 15:15:39:  Processing Hmmer results
04/02/2022 15:15:39:  667725 taxid not found
Traceback (most recent call last):
  File "/data/msb/tools/eukcc/eukcc_env/bin/eukcc", line 8, in <module>
    sys.exit(main())
  File "/data/msb/tools/eukcc/eukcc_env/lib/python3.7/site-packages/eukcc/__main__.py", line 222, in main
    _ = m.inferLineage(m.placements[m.cfg["placementMethod"]])
  File "/data/msb/tools/eukcc/eukcc_env/lib/python3.7/site-packages/eukcc/workflow.py", line 261, in inferLineage
    common = set(lngs[0])
IndexError: list index out of range

**Comment by openpaul** [comment]
I believe you are using EukCC version 1 (3.2 was never released [Not consciously at least], so maybe its 0.3.2), the latest version is EukCC 2, which should be used. 

I am not maintaining the old 1 version anymore. 

I recommend using the latest docker container, which should make installation fast and easy. Please make sure to fetch the latest database as well, as the old one does not work with the new update.

https://github.com/Finn-Lab/EukCC
