### ISSUE TITLE
Question: multicellular eukaryotes?

### ISSUE THREAD

**Issue by Ahmed-Shibl** [Finn-Lab/EukCC#17]
Hi EukCC developers, thanks for this great software - looking forward to using it.

I was wondering if you have tried EukCC on multicellular eukaryotes, e.g. coral genomes? and if so, are there any specific tweaks you would recommend? Thanks in advance!

**Comment by openpaul** [comment]
Hello,
EukCC is trained on genomes of single cellular eukaryotes, so currently it does not work on corals. Its definitively an interesting area but so far not our prime objective :)

**Comment by Ahmed-Shibl** [comment]
Hello,
Thanks for the info.
FYI - I gave it a go the other day on a bin (from an assembly) and got a taxid = Eukaryota_Metazoa_Cnidaria_Anthozoa in the .tsv output. Looked promising but of course I'll have to rely on something more multicellular eukaryote-specific to report results.
