### ISSUE TITLE
No profiles to evaluate?

### ISSUE THREAD

**Issue by franciscozorrilla** [Finn-Lab/EukCC#18]
Hi, thanks for developing and sharing your software.
I am getting the following message when I try running EukCC:
```
eukcc --db /path/to/eukccdb --outdir . --ncorespplacer 1 --ncores 16 input_mag.fa 
03/18/2021 12:33:32:  Starting EukCC
03/18/2021 12:33:33:  Running GeneMark-ES
03/18/2021 13:03:51:  Extracting protein locations
03/18/2021 13:03:51:  Searching for proteins to place in the tree
03/18/2021 13:03:57:  Processing Hmmer results
03/18/2021 13:04:12:  Placing proteins in tree
03/18/2021 13:08:15:  MAG succesfully placed in tree
03/18/2021 13:08:15:  We have no profiles to evaluate
03/18/2021 13:08:15:  No estimates were written
```
I tried looking through the documentation/issues but I cannot determine what the problem is, and I am not sure what `We have no profiles to evaluate` means for me. Have I improperly installed eukcc or are my MAGs simply devoid of any "signal" for eukcc to pick up?

Thank you and best wishes,
Francisco

**Comment by openpaul** [comment]
It means no appropriate single copy marker gene set could be located for your MAG. Could be that its a rare protists, which are under represented or some other factor.

In this case there is currently not much to be done. I hope to make these issues more sparse with an updated version of eukcc.
