### ISSUE TITLE
pip vs pip3 in docs

### ISSUE THREAD

**Issue by hyphaltip** [Finn-Lab/EukCC#5]
May want to indicate that `pip` rather than `pip3` will be the available pip command on a system.

https://github.com/Finn-Lab/EukCC/commit/acfc1dacb6d3ab5cd6c334b7ca1357dc2ad611b0#r38358529

**Comment by openpaul** [comment]
I agree, changed it in the documentation. Added a comment for users where pip is the python 2.7 pip.
https://github.com/Finn-Lab/EukCC/commit/c5787a30b63e07b08d706aaa8d03b060d2d38de6
