### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'hmmsearch'

### ISSUE THREAD

**Issue by openpaul** [Finn-Lab/EukCC#8]
With the current version 0.2 in bioconda pplacer and hmmer are not getting installed. This will be fixed soon, but in case you get this error please make sure to install hmmer and pplacer manually in the conda environment:

```
conda install -c bioconda hmmer pplacer
```
Hope to have this fixed soon.

**Comment by openpaul** [comment]
This should be fixed now

**Comment by OnlineArts** [comment]
I've installed it today following you guide on [readthedocs](https://eukcc.readthedocs.io/en/latest/install.html#quickstart-and-testing) and it failed by:
`pplacer is not installed`
`09/23/2020 12:36:53:  Placing proteins in tree`
`Pplacer failed with unkown reason`

Even your suggested conda install command above does not help. What can I do?
I'm using Ubuntu 18.04 LTS.

**Comment by openpaul** [comment]
It seems pplacer was not installed or loaded by conda. Pplacer needs to be availiable in your path. 

Can you do a 

```
which pplacer
```
And 
```
which hmmsearch
```
Both should give something like `/home/paul/.miniconda3/bin/pplacer`.
If they result in `pplacer not found`, you dont have them installed correctly.

**Comment by OnlineArts** [comment]
Hey Paul, thank you very much. Indeed, it was a problem by conda :-)
I've solved that. Conda did not load correctful the environment. Thank you for your response.
